language: cpp
os: linux
dist: bionic
sudo: false

install:
  - git clone --depth 2 --branch develop --recursive https://github.com/boostorg/boost.git
  - cp root_cmake_file/CMakeLists.txt boost/CMakeLists.txt

script:
  - cmake --version
  - mkdir __out__ && cd __out__
  - cmake --log-level=VERBOSE -DBOOST_MIN_CMAKE_INCLUDE_ALL_TESTS=ON ../boost
  - cmake --build .
  - ctest --output-on-failure .